# Generated by Django 4.2.3 on 2023-08-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('social_media', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=300)),
                ('time', models.DateTimeField()),
                ('image', models.ImageField(default=None, max_length=300, null=True, upload_to='blog_images/')),
            ],
        ),
    ]
