# Generated by Django 4.2.3 on 2023-08-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_info_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_info',
            name='image',
        ),
    ]
