# Generated by Django 4.2.3 on 2023-08-09 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_info_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_info',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog_info',
            name='social_media',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
