# Generated by Django 4.2.3 on 2023-08-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_info_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_info',
            name='social_media',
            field=models.CharField(default='Social Media', max_length=100, null=True),
        ),
    ]
