# Generated by Django 4.2.3 on 2023-08-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_details',
            name='course_poster',
            field=models.ImageField(default=None, max_length=300, null=True, upload_to='courses/'),
        ),
    ]
