# Generated by Django 4.2.3 on 2023-08-02 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_registrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
