# Generated by Django 4.2.3 on 2023-08-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_registrant_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='course_details',
            new_name='course_detail',
        ),
        migrations.RenameField(
            model_name='course_detail',
            old_name='course_details',
            new_name='course_info',
        ),
    ]
